version: '3.9'
services:
  checkers:
    container_name: checkers
    image: checkers:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - fileio
    stdin_open: true
    ports:
      - "8080:8080"
    environment:
      - DISPLAY=host.docker.internal:0.0
      - FILE_IO_HOST=fileio
      - FILE_IO_PORT=8081
      - CHECKERS_UI_TYPE=tui gui rui
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
  fileio:
    container_name: checkers-fileio
    image: checkers-fileio:latest
    build:
      context: .
      dockerfile: Dockerfile-FileIo
    stdin_open: true
    tty: true
    ports:
      - "8081:8081"